services:
  frontend:
    image: ironbad-frontend:latest
    container_name: ironbad-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: ironbad-backend:latest
    container_name: ironbad-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/src/app
    ports:
      - "8000:8000"
    user: root
    restart: always
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15-alpine
    container_name: ironbad-database
    environment:
      POSTGRES_DB: ironbad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
