services:
  frontend:
    image: ironbad-frontend:latest
    container_name: ironbad-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: ironbad-backend:latest
    container_name: ironbad-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/src/app
    ports:
      - "8000:8000"
    user: root
    restart: always
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

  database:
    image: pgvector/pgvector:pg15
    container_name: ironbad-database
    environment:
      POSTGRES_DB: ironbad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: ironbad-redis
    ports:
      - "6379:6379"
    restart: always

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ironbad-redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db
    environment:
      - RI_APP_HOST=0.0.0.0
      - RI_APP_PORT=5540
      - RI_LOG_LEVEL=info
      - RI_ACCEPT_TERMS_AND_CONDITIONS=true
    restart: always
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5540"]
      interval: 10s
      timeout: 5s
      retries: 3

  taskiq-worker:
    image: ironbad-backend:latest
    container_name: ironbad-taskiq-worker
    command: uv run taskiq worker app.features.workflows.tasks:broker --reload --max-async-tasks=10 --max-prefetch=5
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
      backend:
        condition: service_started
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/src/app
    restart: always

volumes:
  postgres_data:
  redis_insight_data:
